name: integracion_moviles
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.8
  mobile_scanner: ^3.0.0
  cupertino_icons: ^1.0.8
  geolocator: ^9.0.0
  speech_to_text: ^7.0.0 
  flutter_tts: ^3.4.0 # Asegúrate de tener esta línea
  permission_handler: ^11.3.1
  shared_preferences: ^2.0.13
  sensors_plus: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Logo.jpg
